---
title: "Exec report"
author: "EGN Sverige AB"
date:
output:
  html_document:
    depth: 3
    highlight: tango
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 1
    fig_width: 8
    fig_height: 4
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load data, echo=FALSE, message=FALSE, warning=FALSE}
#Data used for this report:
#Statistik per uge (Members in/out)
#Member statistics (Avg mem/group + retention)
#Renewals (Renewals)
#Product performance (Grupper)
#KPI Member Services (NPS)

#Df and plot for Members in/out
load(file="dft.RData")
load(file="t.RData")
#Df and plot for retention
load(file="churndf.RData")
load(file="c.RData")
#Df and plot RYG groups
load(file="RYGdf2.RData")
load(file="Totalgroup.RData")
load(file="o.RData")
#Df and plot renewals
load(file="renewaldf.RData")
load(file="i.RData")
#Df and plot average members
load(file="avgmemdf.RData")
load(file="u.RData")
load(file="week.RData")
#Df and plot NPS
load(file="NPSRoll.RData")
load(file="n.RData")


```
Vecka `r week`

#Medlemmar in/ut per vecka
```{r Medlemmar in/ut, echo=FALSE, message=FALSE, warning=FALSE}
options(warn = -1)
t
```

<br><br/>

#Average Members/grupp
```{r Average members, echo=FALSE}
u
```

<br><br/>

#Retention - (%)

```{r Retention, echo=FALSE}
c
```

<br><br/>

#Renewals (Antal/mn)
```{r Renewals, echo=FALSE}
i
```


<br><br/>

#Grupper
```{r Grupper, echo=FALSE}
o
```
  
<br><br/>

#NPS - (% som svarar 9-10/Rullande 12 mn)
```{r NPS, echo=FALSE}
n
```
